[package]
name = "arcaders"
version = "0.1.0"
authors = ["alanpoon"]

[dependencies]
rand = "0.3"

[dependencies.sdl2]
version = "0.29"
default-features = false
features = ["ttf","image","gfx","mixer"]